---
title: "Extract New Confirmed Case Data from China"
author: "Kylie Ainslie"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    fig_width: 7
    fig_height: 5
    fig_caption: true
    highlight: "tango"
    reference_docx: word_style.docx
---

```{r read_in_google_sheet}
sheets_deauth()
url <- "https://docs.google.com/spreadsheets/d/1nQPYCdJjPy8foKrbWOZVkZ-DacE-5ESGYe0xo-c7Hyk/edit#gid=0"

sheets <- sheets_sheets(url)

out1 <- sheets_read(url, sheet = 1)
out1 <- clean_names(out1)

out2 <- sheets_read(url, sheet = 2)
out2 <- clean_names(out2)
```

```{r imported_data_wrangling}
# subset for top 5 and beijing
case_dat1 <- out1 %>% 
              #select(date_confirm, hubei, guangdong, henan, zhejiang, hunan, beijing) %>%
              gather(province, new_cases, hubei:macau_sar)
case_dat2 <- out2 %>% 
              #select(date_confirm, hubei, guangdong, henan, zhejiang, hunan, beijing) %>%
              gather(province, imported_cases, hubei:macau_sar) 
case_dat <- left_join(case_dat1, case_dat2, by = c("date_confirm", "province")) %>%
              mutate(imported_cases = ifelse(is.na(imported_cases), 0, imported_cases),
                     new_cases_wo_imported = new_cases - imported_cases)
```

```{r}
# Output file
write_csv(out1, "china_new_case_data.csv")
write_csv(case_dat, "china_new_case_data_imported.csv")
```